# -*- coding: utf-8 -*-
""" Solocoo API """
from __future__ import absolute_import, division, unicode_literals

SOLOCOO_API = 'https://tvapi.solocoo.tv/v1'

CAPI_API = 'https://m7be2.solocoo.tv/m7be2iphone/capi.aspx'  # TODO: use tenant

# Source: https://livetv.tv-vlaanderen.be/static/js/common/structures/Channel.ts (via source map)

# EPG program bits
BIT_EPG_DETAIL_ID = 1
BIT_EPG_DETAIL_TITLE = 2
BIT_EPG_DETAIL_DESCRIPTION = 8
BIT_EPG_DETAIL_AGE = 16
BIT_EPG_DETAIL_CATEGORY = 32
BIT_EPG_DETAIL_START = 64
BIT_EPG_DETAIL_END = 128
BIT_EPG_DETAIL_FLAGS = 256
BIT_EPG_DETAIL_GENRE = 512
BIT_EPG_DETAIL_COVER = 1024
BIT_EPG_DETAIL_SEASON_NO = 2048
BIT_EPG_DETAIL_EPISODE_NO = 4096
BIT_EPG_DETAIL_SERIES_ID = 8192
BIT_EPG_DETAIL_SG = 16384
BIT_EPG_DETAIL_CHANEL_NAME = 32768
BIT_EPG_DETAIL_GENRES = 65536
BIT_EPG_DETAIL_CREDITS = 131072
BIT_EPG_DETAIL_FORMAT = 262144
BIT_EPG_DETAIL_FORMATS = 524288
BIT_EPG_DETAIL_AIRDATE = 16777216

# EPG program flags
BIT_EPG_FLAG_LIVE = 1
BIT_EPG_FLAG_REPEAT = 2
BIT_EPG_FLAG_HIGHLIGHT = 4
BIT_EPG_FLAG_LMU = 8
BIT_EPG_FLAG_REPLAY = 16
BIT_EPG_FLAG_RESTART = 32
BIT_EPG_FLAG_RECORD = 64

# Channel detail bits
BIT_CHANNEL_DETAIL_ID = 1
BIT_CHANNEL_DETAIL_NUMBER = 2
BIT_CHANNEL_DETAIL_STATIONID = 4
BIT_CHANNEL_DETAIL_TITLE = 8
BIT_CHANNEL_DETAIL_16 = 16  # Unknown
BIT_CHANNEL_DETAIL_GENRES = 32
BIT_CHANNEL_DETAIL_FLAGS = 64
BIT_CHANNEL_DETAIL_URL = 128  # Unknown
BIT_CHANNEL_DETAIL_DVBS = 256  # 3:3225:21025:235
BIT_CHANNEL_DETAIL_SDSD = 2048  # 430B0121870002359602990002

# Channel detail flags
BIT_CHANNEL_FLAG_RECORDABLE = 2
BIT_CHANNEL_FLAG_EXTERNAL = 8
BIT_CHANNEL_FLAG_RADIO = 16
BIT_CHANNEL_FLAG_DISALLOW_WIFI = 32
BIT_CHANNEL_FLAG_DISALLOW_3G = 64
BIT_CHANNEL_FLAG_PIN = 256
BIT_CHANNEL_FLAG_RESTARTABLE = 512
BIT_CHANNEL_FLAG_HD = 1024
BIT_CHANNEL_FLAG_REPLAYABLE = 2048
BIT_CHANNEL_FLAG_NOT_SCHEDULED = 4096
BIT_CHANNEL_FLAG_BLACKOUT = 8192
BIT_CHANNEL_FLAG_DISALLOW_MIRROR = 16384
BIT_CHANNEL_FLAG_INHOME = 32768
BIT_CHANNEL_FLAG_DISALLOW_RECORD_FF = 524288
BIT_CHANNEL_FLAG_DISALLOW_REPLAY_FF = 1048576
BIT_CHANNEL_FLAG_DISALLOW_RESTART_FF = 2097152
BIT_CHANNEL_FLAG_HAS_FF_RESTRICTIONS = 4194304


TENANTS = dict([
    ('tvv', dict(
        name='TV Vlaanderen',
        domain='livetv.tv-vlaanderen.be',
        env='m7be2iphone',
        app='tvv',
    )),
    ('cds', dict(
        name='Canal Digitaal',
        domain='livetv.canaldigitaal.nl',
        env='m7be2iphone',
        app='cds',
    )),
    # and many more, ...
])
